sudo: required
language: python
python:
  - "2.7"
  - "3.6"

cache:
  - pip
  - yarn

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

install:
  - make init

script:
  - make test

after_success:
  - codecov --token=915ec5cf-c922-43df-a4f7-2e35a7674826

notifications:
  email: false